import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { Menu, Navbar } from "@/components/ui";
import Global from "@/components/Global";
import { NavMenuProvider } from "@/state/navMenuState/navMenuContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Global />
        <NavMenuProvider>
          <Navbar />
          <Menu />
        </NavMenuProvider>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
