import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { Plus_Jakarta_Sans as PJSans } from "next/font/google";

const pjSans = PJSans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pjSans.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
