import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { Navbar } from "@/components/ui";
import Global from "@/components/Global";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Global />
        <Navbar />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
